public_health_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'ph_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'ph_pass') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'public_health_warehouse') }}"
      schema: warehouse
      threads: 4
